version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test123PrProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/Test123PrProject
  gitUsername: PoojaAnandGit
  gitBranch: main
